apiVersion: v1
kind: ReplicationController
metadata:
  name: kubehello-rc
spec:
  replicas: 5
  selector:
    app: kubeworld
  template:
    metadata:
      labels:
        app: kubeworld
    spec:
      containers:
      - name: kubehelloworld
        image: tianyuyang/kubelearn
        ports:
        - containerPort: 8080
