apiVersion: v1
kind: Pod
metadata:
  name: mongodbtest-pvc
spec:
  containers:
  - image: mongo
    name: mongodb-container-pvc
    volumeMounts:
    - name: mongodb-datavolume
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-datavolume
    persistentVolumeClaim:
      claimName: dbtest-pvc
