apiVersion: v1
kind: Pod
metadata:
  name: mongodbtest
spec:
  volumes:
  - name: mongodb-data-volume
    gcePersistentDisk:
      pdName: dbtester
      fsType: ext4
  containers:
  - image: mongo
    name: mongodb-container
    volumeMounts:
    - name: mongodb-data-volume
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
