apiVersion: v1
kind: Pod
metadata:
  name: secretfortune
  labels:
    app: secretfortuneteller
spec:
  containers:
  - image: tianyuyang/hellofortune
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: config
      mountPath: /tmp/entire-fortune-config-volume
      readOnly: true
    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: fortune-secret-config
  - name: certs
    secret:
      secretName: fortune-https
